version: "3.6"

services:

  app:
    build: .
    tty: true
    volumes:
      - .:/usr/src/ai-chatbot
    depends_on:
      - db
      
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin12345