services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/ai-bot-app

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin12345
